# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RapidThesisQ' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for RapidThesisQ
  pod 'Firebase/Core'
  pod 'Firebase/Database'
  pod 'Firebase/Auth'
  pod 'TextFieldEffects'
  pod 'IQKeyboardManagerSwift'
  pod 'Firebase/Storage'
  pod 'SDWebImage'

end
